### ISSUE TITLE
Getting IIS Directory Information 

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/ExchangeLogCollector#11]
Get-WebConfigurationProperty doesn't appear to work inside of Invoke-Command like I thought it would. Need to verify and come up with a workaround for this.

**Comment by dpaulson45** [comment]
Tested this out, and it should work just fine. Need to have access to someone's where this is changed to a different location.

**Comment by ParaGlideRocks** [comment]
I'll test it and let you know.

**Comment by dpaulson45** [comment]
That would be awesome. Thank you!

**Comment by ParaGlideRocks** [comment]
This is the piece of code I use to setup a new directory for logs:

$NewIISlog = "<DRIVE>:\<Directory" #These are placeholders
New-Item -type directory -path $NewIISlog -Force 
get-itemproperty IIS:\Sites\* | ForEach-Object {
$SiteName = $_.Name
Set-ItemProperty "IIS:\Sites\$SiteName" -name logfile.directory "$NewIISlog\$SiteName"  }

**Comment by dpaulson45** [comment]
Yeah, so when doing it that way we aren't getting the correct directory location from the following line in the script: 

 $Script:IISLogDirectory = ((Get-WebConfigurationProperty "system.applicationHost/sites/siteDefaults" -Name logFile).directory).Replace("%SystemDrive%",$env:SystemDrive) 

There is going to be a problem running that cmdlet within Invoke-Command - see the following. 

##########################

PS C:\Users\administrator.VNEXT> Get-Website

Name             ID   State      Physical Path                  Bindings
----             --   -----      -------------                  --------
Default Web Site 1    Started    %SystemDrive%\inetpub\wwwroot  http *:80:
                                                                net.tcp 808:*
                                                                net.pipe *
                                                                net.msmq localhost
                                                                msmq.formatname localhost
                                                                https :443: sslFlags=0
                                                                http 127.0.0.1:80:
                                                                https 127.0.0.1:443: sslFlags=0
Exchange Back    2    Started    C:\Program                     http *:81:
End                              Files\Microsoft\Exchange       https *:444: sslFlags=0
                                 Server\V15\ClientAccess        net.pipe *


PS C:\Users\administrator.VNEXT> Invoke-Command -ComputerName $env:COMPUTERNAME -ScriptBlock {Get-WEbsite}

Name             ID   State      Physical Path                  Bindings                    PSComputerName
----             --   -----      -------------                  --------                    --------------
Default Web Site 1    Started                                   http *:80:                  VNEXT-E2K13AIO1
                                                                net.tcp 808:*
The data is invalid. (Exception from HRESULT: 0x8007000D)
    + CategoryInfo          : NotSpecified: (:) [Get-Website], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.IIs.PowerShell.Provider.GetWebsite
   Command
    + PSComputerName        : VNEXT-E2K13AIO1

##########################

Need to figure out how to address this here.

**Comment by dpaulson45** [comment]
Verify this is resolved in v2.5
