### ISSUE TITLE
An error occurred in Remote-Functions

### ISSUE THREAD

**Issue by ParaGlideRocks-zz** [dpaulson45/ExchangeLogCollector#115]
I'm getting this error

[EX2013] : An error occurred in Remote-Functions
[EX2013] : Error Exception: System.Management.Automation.RemoteException: ERROR: An unexpected error occurred.
[EX2013] : Error Stack: at Save-ServerInfoData, <No file>: line 963
at <ScriptBlock>, <No file>: line 1
at Remote-Main, <No file>: line 1945
at <ScriptBlock>, <No file>: line 1962

when running the scritp this way

.\ExchangeLogCollector.ps1 -FilePath C:\Users\Administrator.CONTOSO\Downloads\ELC -Servers exc2010,ex2013,ex2016a -DailyPerformanceLogs -ManagedAvailability -HighAvailabilityLogs -ADDriverLogs -DAGInformation -GetVdirs -MessageTrackingLogs -OrganizationConfig -TransportConfig -ServerInfo -DaysWorth 3 -CollectAllLogsBasedOnDaysWorth -Verbose

**Comment by dpaulson45** [comment]
@ParaGlideRocks  can you -ScriptDebug and provide the output on the screen?

**Comment by ParaGlideRocks** [comment]
[HealthCheckerDebugLog.txt](https://github.com/dpaulson45/ExchangeLogCollector/files/3826989/HealthCheckerDebugLog.txt)

**Comment by dpaulson45** [comment]
```
[EX2013 - Script Debug] : Calling: Save-DataToFile
[EX2013 - Script Debug] : Passed: [string]SaveToLocation: C:\Users\Administrator.CONTOSO\Downloads\ELC\2019116\EX2013\General_Server_Info\EX2013_FLTMC_Instances | [bool]FormatList: True | [bool]SaveTextFile: True | [bool]SaveXMLFile: False | [scriptblock]VerboseFunctionCaller: True
[EX2013 - Script Debug] : Took 0.0156029 seconds to save out the data.
[EX2013 - Script Debug] : Calling: Add-ServerNameToFileName
[EX2013 - Script Debug] : Passed: [string]FilePath: C:\Users\Administrator.CONTOSO\Downloads\ELC\2019116\EX2013\General_Server_Info\Exchange_Registry_Hive
[EX2013 - Script Debug] : Returned: C:\Users\Administrator.CONTOSO\Downloads\ELC\2019116\EX2013\General_Server_Info\EX2013_Exchange_Registry_Hive
[EX2013 - Script Debug] : Calling: Save-DataToFile
[EX2013 - Script Debug] : Passed: [string]SaveToLocation: C:\Users\Administrator.CONTOSO\Downloads\ELC\2019116\EX2013\General_Server_Info\EX2013_Exchange_Registry_Hive | [bool]FormatList: True | [bool]SaveTextFile: False | [bool]SaveXMLFile: True | [scriptblock]VerboseFunctionCaller: True
[EX2013 - Script Debug] : Took 4.2180706 seconds to save out the data.
[EX2013] : An error occurred in Remote-Functions
[EX2013] : Error Exception: System.Management.Automation.RemoteException: ERROR: An unexpected error occurred.
[EX2013] : Error Stack: at Save-ServerInfoData, <No file>: line 963
at <ScriptBlock>, <No file>: line 1
at Remote-Main, <No file>: line 1945
at <ScriptBlock>, <No file>: line 1962
[EX2013 - Script Debug] : Exiting: Remote-Functions
```

Need to look into this to determine why we are failing to get information to save out. Might need to include some additional debug data.

**Comment by dpaulson45** [comment]
We might not be able to collect the logs, but all other logs that we attempt to be collected should work just fine. Added a try catch around each log type collection here.

ffdb4a8b8f488634e3b66f5fe6b65c62da712b9f
