### ISSUE TITLE
When sending large objects to Invoke-Command get PSRemotingTransportException back

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/ExchangeLogCollector#29]
Getting the following error message when trying to run invoke-command: 

Sending data to a remote command failed with the following error message: The current deserialized object size of the data received from the remote
client computer exceeded the allowed maximum object size. The current deserialized object size is 10572800. The allowed maximum object size is
10485760. For more information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OperationStopped: (ServerNameString) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : ServerName

This is likely due to the number of databases and servers within the DAG. Need to have the DAG information stored in a different variable for the time being then written out at the end of the script.

**Comment by dpaulson45** [comment]
Pending for some additional testing

**Comment by ParaGlideRocks** [comment]
You can close this bug. I've tested version 2.5 and it worked.

**Comment by dpaulson45** [comment]
Confirmed that this is working. Closing issue.

**Comment by dpaulson45** [comment]
Issue doesn't fully appear to be resolved..... need to dig into this some more

**Comment by dpaulson45** [comment]
It appears that I actually have a lab now that can reproduce this issue consistently. Going to attempt to dig more into this in order to resolve this issue.

**Comment by dpaulson45** [comment]
So i was able to prevent this to occur by not including the large object types of HealthReport and ServerComponentState to the server objects that are passed within ArgumentList parameter of the Invoke-Command. Going to need to figure out how to not include this in the ArgumentList. 

Hopefully this is the only reason why this is occurring, as I really don't want to fully redo the script to chunk up the Scripting Block as well.

**Comment by harishKumarMS** [comment]
Do we have any kind of solution regarding this error : 

new-dlpsensitiveinformationtyperulepackage -Filedata (Get-Content -Path "c:\xxx\xxx\xxx_Rules.xml" -Encoding Byte)


Error :
Sending data to a remote command failed with the following error message: The current deserialized object size of the data received from remote client exceeded allowed maximum object size. The current deserialized object size is 10572800. Allowed maximum object size is 10485760
