### ISSUE TITLE
Collect tracking log files

### ISSUE THREAD

**Issue by ParaGlideRocks** [dpaulson45/ExchangeLogCollector#51]
It should be useful to collect tracking logs for statistical purposes (messages sent/received…)

**Comment by dpaulson45** [comment]
Are you talking about Message tracking logs? If so, i am already collecting them.

**Comment by dpaulson45** [comment]
@ParaGlideRocks can you please provide what you are talking about for this request?

**Comment by ParaGlideRocks** [comment]
Hi @dpaulson45 I was speaking about Message Tracking Logs as well.
