### ISSUE TITLE
DailyPerformanceLogs outside default path

### ISSUE THREAD

**Issue by ParaGlideRocks-zz** [dpaulson45/ExchangeLogCollector#99]
Detect and collect DLP outside their default path.

**Comment by dpaulson45** [comment]
How are people moving the daily performance logs? Wasn't aware of a way to change this.

**Comment by dpaulson45** [comment]
@ParaGlideRocks can you provide how you move the daily performance logs.

**Comment by ParaGlideRocks** [comment]
Hi David,
you can query the actual position of DailyPerformanceLogs with logman.

logman query

Data Collector Set                      Type                          Status
-------------------------------------------------------------------------------
CavePerformance_EX2013.FTS.COM          Counter                       Undefined
ExchangeDiagnosticsDailyPerformanceLog  Counter                       Undefined
ExchangeDiagnosticsPerformanceLog       Counter                       Undefined

The command completed successfully.


logman query ExchangeDiagnosticsDailyPerformanceLog | more

Name:                 ExchangeDiagnosticsDailyPerformanceLog
Status:               Stopped
Root Path:            C:\Program Files\Microsoft\Exchange Server\V15\Logging\Diagnostics\DailyPerformanceLogs
Segment:              On
Schedules:            On
Segment Max Duration: 86400 second(s)
Run as:               SYSTEM

Name:                 ExchangeDiagnosticsDailyPerformanceLog\ExchangeDiagnosticsDailyPerformanceLog
Type:                 Counter
Output Location:      C:\Program Files\Microsoft\Exchange Server\V15\Logging\Diagnostics\DailyPerformanceLogs\ExchangeDi
agnosticsDailyPerformanceLog_05201554.blg
Append:               Off
Circular:             Off
Overwrite:            Off
Sample Interval:      60 second(s)

To change path:

logman -stop ExchangeDiagnosticsDailyPerformanceLog
logman -update ExchangeDiagnosticsDailyPerformanceLog -o “H:\Exchange\PerformanceLogs”
logman -start ExchangeDiagnosticsDailyPerformanceLog

Regards
Mn

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dpaulson45** [comment]
@ParaGlideRocks thanks for the update. I will have to include some additional logic for this.
